### ISSUE TITLE
Problem with drawer attaching on login.

### ISSUE THREAD

**Issue by akircher** [dscsa/client#124]
``` 
 MdDrawerCustomElement.prototype.attached = function attached() {
      this.header = document.querySelector('.mdl-layout__header');
      this.header.parentNode.insertBefore(drawer, this.header.nextSibling);

      componentHandler.upgradeAllRegistered();

      this.button = document.querySelector('.mdl-layout__drawer-button');
      this.button.style.display = 'block';

      if (this.autofocus) this.header.firstChild.click();
    };
```

Unhandled rejection TypeError: Cannot read property 'style' of null
    at MdDrawerCustomElement.attached (http://v2.sirum.org/assets/app-bundle.js:215:18)
    at Controller.attached (http://v2.sirum.org/assets/vendor-bundle.js:20539:24)
    at View.attached (http://v2.sirum.org/assets/vendor-bundle.js:18656:24)
    at ViewSlot.add (http://v2.sirum.org/assets/vendor-bundle.js:18819:14)
    at http://v2.sirum.org/assets/vendor-bundle.js:25161:29
From previous event:
    at http://v2.sirum.org/assets/vendor-bundle.js:25159:30
From previous event:
    at after (http://v2.sirum.org/assets/vendor-bundle.js:25044:56)
    at work (http://v2.sirum.org/assets/vendor-bundle.js:25143:9)
    at http://v2.sirum.org/assets/vendor-bundle.js:25173:18
From previous event:
    at RouterView.swap (http://v2.sirum.org/assets/vendor-bundle.js:25171:87)
    at http://v2.sirum.org/assets/vendor-bundle.js:15513:29
    at Array.forEach (native)
    at http://v2.sirum.org/assets/vendor-bundle.js:15512:20
From previous event:
    at NavigationInstruction._commitChanges (http://v2.sirum.org/assets/vendor-bundle.js:15511:33)
    at CommitChangesStep.run (http://v2.sirum.org/assets/vendor-bundle.js:15360:36)
    at next (http://v2.sirum.org/assets/vendor-bundle.js:15329:20)
    at iterate (http://v2.sirum.org/assets/vendor-bundle.js:16413:14)
    at inspect (http://v2.sirum.org/assets/vendor-bundle.js:16384:16)
    at http://v2.sirum.org/assets/vendor-bundle.js:16402:24
From previous event:
    at processPotential (http://v2.sirum.org/assets/vendor-bundle.js:16494:35)
    at http://v2.sirum.org/assets/vendor-bundle.js:16401:18
    at iterate (http://v2.sirum.org/assets/vendor-bundle.js:16405:12)
    at processActivatable (http://v2.sirum.org/assets/vendor-bundle.js:16416:12)
    at ActivateNextStep.run (http://v2.sirum.org/assets/vendor-bundle.js:16297:14)
    at next (http://v2.sirum.org/assets/vendor-bundle.js:15329:20)
    at iterate (http://v2.sirum.org/assets/vendor-bundle.js:16326:14)
    at processDeactivatable (http://v2.sirum.org/assets/vendor-bundle.js:16329:12)
    at DeactivatePreviousStep.run (http://v2.sirum.org/assets/vendor-bundle.js:16285:14)
    at next (http://v2.sirum.org/assets/vendor-bundle.js:15329:20)
    at iterate (http://v2.sirum.org/assets/vendor-bundle.js:16413:14)
    at processActivatable (http://v2.sirum.org/assets/vendor-bundle.js:16416:12)
    at CanActivateNextStep.run (http://v2.sirum.org/assets/vendor-bundle.js:16273:14)
    at next (http://v2.sirum.org/assets/vendor-bundle.js:15329:20)
    at http://v2.sirum.org/assets/app-bundle.js:1697:35
From previous event:
    at AuthorizeStep.run (http://v2.sirum.org/assets/app-bundle.js:1672:34)
From previous event:
    at LoadRouteStep.run (http://v2.sirum.org/assets/vendor-bundle.js:16560:68)
    at next (http://v2.sirum.org/assets/vendor-bundle.js:15329:20)
    at iterate (http://v2.sirum.org/assets/vendor-bundle.js:16326:14)
    at processDeactivatable (http://v2.sirum.org/assets/vendor-bundle.js:16329:12)
    at CanDeactivatePreviousStep.run (http://v2.sirum.org/assets/vendor-bundle.js:16261:14)
    at next (http://v2.sirum.org/assets/vendor-bundle.js:15329:20)
    at http://v2.sirum.org/assets/vendor-bundle.js:15765:16
From previous event:
    at BuildNavigationPlanStep.run (http://v2.sirum.org/assets/vendor-bundle.js:15763:58)
    at next (http://v2.sirum.org/assets/vendor-bundle.js:15329:20)
    at Pipeline.run (http://v2.sirum.org/assets/vendor-bundle.js:15342:14)
    at http://v2.sirum.org/assets/vendor-bundle.js:16889:25
From previous event:
    at AppRouter._dequeueInstruction (http://v2.sirum.org/assets/vendor-bundle.js:16862:32)
    at http://v2.sirum.org/assets/vendor-bundle.js:16853:17
From previous event:
    at AppRouter._queueInstruction (http://v2.sirum.org/assets/vendor-bundle.js:16850:14)
    at http://v2.sirum.org/assets/vendor-bundle.js:16784:23
From previous event:
    at AppRouter.loadUrl (http://v2.sirum.org/assets/vendor-bundle.js:16783:53)
    at BrowserHistory._loadUrl (http://v2.sirum.org/assets/vendor-bundle.js:12155:55)
    at BrowserHistory.navigate (http://v2.sirum.org/assets/vendor-bundle.js:12111:21)
    at AppRouter.navigate (http://v2.sirum.org/assets/vendor-bundle.js:15977:27)
    at http://v2.sirum.org/assets/app-bundle.js:1466:23
From previous event:
    at login (http://v2.sirum.org/assets/app-bundle.js:1465:10)
    at CallScope.evaluate (http://v2.sirum.org/assets/vendor-bundle.js:6563:21)
    at Listener.callSource (http://v2.sirum.org/assets/vendor-bundle.js:9992:42)
    at http://v2.sirum.org/assets/vendor-bundle.js:10016:24
    at HTMLDocument.handleDelegatedEvent (http://v2.sirum.org/assets/vendor-bundle.js:8209:7)
    at MdButtonCustomElement.click (http://v2.sirum.org/assets/app-bundle.js:69:49)
    at CallScope.evaluate (http://v2.sirum.org/assets/vendor-bundle.js:6563:21)
    at Listener.callSource (http://v2.sirum.org/assets/vendor-bundle.js:9992:42)
    at http://v2.sirum.org/assets/vendor-bundle.js:10016:24
    at HTMLDocument.handleDelegatedEvent (http://v2.sirum.org/assets/vendor-bundle.js:8209:7)

**Comment by akircher** [comment]
Appear to be fixed
